### PR TITLE
Mutable source code item

### PR DESCRIPTION
**Pull request by shaharyakir**

### CODE REVIEW

**Comment by cumcum8197** [comment]
81dfc74fa9efe7854a0b50fea1bd2ea35a770a39

**Comment by cumcum8197** [comment]
81dfc74fa9efe7854a0b50fea1bd2ea35a770a39

**Review by Gioviii78 — COMMENTED** [review]
Gg

**Comment by cumcum8197** [comment]
81dfc74fa9efe7854a0b50fea1bd2ea35a770a39

**Comment by cumcum8197** [comment]
81dfc74fa9efe7854a0b50fea1bd2ea35a770a39

**Pull request merged**
