### PR TITLE
Set deployment costs

### PR DESCRIPTION
**Pull request by shaharyakir**

### CODE REVIEW

**Review by Kingjayveeoner — COMMENTED** [review]
</will-is-way>

**Comment by cumcum8197** [comment]
0328e11b84892c7e714435b8bfc2b3c767c1e5b1

**Comment by cumcum8197** [comment]
0328e11b84892c7e714435b8bfc2b3c767c1e5b1

**Comment by cumcum8197** [comment]
0328e11b84892c7e714435b8bfc2b3c767c1e5b1

**Pull request merged**
