### PR TITLE
sources admin

### PR DESCRIPTION
**Pull request by shaharyakir**
1. Added value validation (0.5TON < val < 1TON)
2. Added set source item code op
3. Non-sequential op codes
4. Non-empty set code validation

### CODE REVIEW

**Review by Kingjayveeoner — COMMENTED** [review]
?

**Comment by cumcum8197** [comment]
80f83249837fc62c9a6af66ad1c1490f00ebeef1

**Comment by cumcum8197** [comment]
80f83249837fc62c9a6af66ad1c1490f00ebeef1

**Comment by cumcum8197** [comment]
80f83249837fc62c9a6af66ad1c1490f00ebeef1

**Pull request merged**
